# Workflow name
name: First Workflow

# Controls when the action will run. Triggers the workflow on push or pull request\
on: workflow_dispatch
# on: 
#     push:
#         branches: [ "main" ]
# pull_request:
#     branches: [ "main" ]

jobs:
  first_job:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-latest
    steps:
        - name: Print greeting
          run: echo "Hello, world!"
        - name: Print Good bye!
          run: echo "Good bye!"

