name: Python application test with pytest

on: workflow_dispatch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    # strategy:
    #     fail-fast: false
    #     matrix:
    #       python-version: ["3.8", "3.10", "3.11"]
    steps:

    - name: Check Out
      # https://github.com/actions/checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.branch }}
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config --global user.email "nhonquy@gmail.com"
        git config --global user.name "GitHub Actions"

    - name: Set up Python 3.8.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.8.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pytest-html
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run tests with pytest
      run: |
        pytest
    # - name: Upload coverage to Codecov
#   uses: codecov/codecov-action@v4
#   with:
#     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
#     file: ./reports/coverage/coverage.xml # optional
#     flags: unittests # optional
#     name: codecov-umbrella # optional
#     fail_ci_if_error: true # optional
# - name: Upload HTML report
#   uses: actions/upload-artifact@v2
#   with:
#     name: pytest-report
#     path: ./reports/html/summary.html
